linter: added discardVar check
VKCOM/noverify pull request #826
Opened 2020-11-30 17:46 UTC by i582

2020-11-30 19:41 UTC, YuriyNasretdinov approved these changes

2020-11-30 20:14 UTC, quasilyte requested changes
Please add tests for cases that only work correctly due to the implementation detail.
If we ever split checkers and will run them separately, this code might break otherwise without us noticing it.

* list args - `list ($_unused, ...) = $rhs`; `$_unused` is not a usage
* lambda params - `$f = function($_unused, $x) {...}`; `$_unused` is not a usage
* same for arrow function params

There might be other interesting cases.

2020-11-30 20:16 UTC, quasilyte commented on src/linter/block.go
> +			b.r.Report(v, LevelError, "discardVar", "Used discard variable $%s value (rename variable if it's intended)", varName)
"discard value" is our own term which won't be too obvious for the users.

How about this message:
```
Used var that is supposed to be unused (rename variable if it's intended)
```

2020-12-01 12:04 UTC, quasilyte approved these changes

2020-12-01 12:04 UTC, merged